/*
 * SendGrid v3 API Documentation
 *
 * # The SendGrid Web API V3 Documentation  This is the entirety of the documented v3 endpoints. We have updated all the descriptions, parameters, requests, and responses.  ## Authentication   Every endpoint requires Authentication in the form of an Authorization Header:  Authorization: Bearer API_KEY
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package generated_type

// Settings to determine how you would like to track the metrics of how your recipients interact with your email.
type MailsendTrackingSettings struct {

	ClickTracking *MailsendTrackingSettingsClickTracking `json:"click_tracking,omitempty"`

	OpenTracking *MailsendTrackingSettingsOpenTracking `json:"open_tracking,omitempty"`

	SubscriptionTracking *MailsendTrackingSettingsSubscriptionTracking `json:"subscription_tracking,omitempty"`

	Ganalytics *MailsendTrackingSettingsGanalytics `json:"ganalytics,omitempty"`
}
