/*
 * SendGrid v3 API Documentation
 *
 * # The SendGrid Web API V3 Documentation  This is the entirety of the documented v3 endpoints. We have updated all the descriptions, parameters, requests, and responses.  ## Authentication   Every endpoint requires Authentication in the form of an Authorization Header:  Authorization: Bearer API_KEY
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package generated_type

type MailsendContent struct {

	// The mime type of the content you are including in your email. For example, “text/plain” or “text/html”.
	Type_ string `json:"type"`

	// The actual content of the specified mime type that you are including in your email.
	Value string `json:"value"`
}
