/*
 * SendGrid v3 API Documentation
 *
 * # The SendGrid Web API V3 Documentation  This is the entirety of the documented v3 endpoints. We have updated all the descriptions, parameters, requests, and responses.  ## Authentication   Every endpoint requires Authentication in the form of an Authorization Header:  Authorization: Bearer API_KEY
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package generated_type

type MailsendAttachments struct {

	// The Base64 encoded content of the attachment.
	Content string `json:"content"`

	// The mime type of the content you are attaching. For example, “text/plain” or “text/html”.
	Type_ string `json:"type,omitempty"`

	// The filename of the attachment.
	Filename string `json:"filename"`

	// The content-disposition of the attachment specifying how you would like the attachment to be displayed. For example, “inline” results in the attached file being displayed automatically within the message while “attachment” results in the attached file requiring some action to be taken before it is displayed (e.g. opening or downloading the file).
	Disposition string `json:"disposition,omitempty"`

	// The content id for the attachment. This is used when the disposition is set to “inline” and the attachment is an image, allowing the file to be displayed within the body of your email.
	ContentId string `json:"content_id,omitempty"`
}
