/*
 * SendGrid v3 API Documentation
 *
 * # The SendGrid Web API V3 Documentation  This is the entirety of the documented v3 endpoints. We have updated all the descriptions, parameters, requests, and responses.  ## Authentication   Every endpoint requires Authentication in the form of an Authorization Header:  Authorization: Bearer API_KEY
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package generated_type

// This allows you to have a blind carbon copy automatically sent to the specified email address for every email that is sent.
type MailsendMailSettingsBcc struct {

	// Indicates if this setting is enabled.
	Enable bool `json:"enable,omitempty"`

	// The email address that you would like to receive the BCC.
	Email string `json:"email,omitempty"`
}
