/*
 * SendGrid v3 API Documentation
 *
 * # The SendGrid Web API V3 Documentation  This is the entirety of the documented v3 endpoints. We have updated all the descriptions, parameters, requests, and responses.  ## Authentication   Every endpoint requires Authentication in the form of an Authorization Header:  Authorization: Bearer API_KEY
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package generated_type

// This allows you to test the content of your email for spam.
type MailsendMailSettingsSpamCheck struct {

	// Indicates if this setting is enabled.
	Enable bool `json:"enable,omitempty"`

	// The threshold used to determine if your content qualifies as spam on a scale from 1 to 10, with 10 being most strict, or most likely to be considered as spam.
	Threshold int32 `json:"threshold,omitempty"`

	// An Inbound Parse URL that you would like a copy of your email along with the spam report to be sent to.
	PostToUrl string `json:"post_to_url,omitempty"`
}
