/*
 * SendGrid v3 API Documentation
 *
 * # The SendGrid Web API V3 Documentation  This is the entirety of the documented v3 endpoints. We have updated all the descriptions, parameters, requests, and responses.  ## Authentication   Every endpoint requires Authentication in the form of an Authorization Header:  Authorization: Bearer API_KEY
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package generated_type

// Allows you to insert a subscription management link at the bottom of the text and html bodies of your email. If you would like to specify the location of the link within your email, you may use the substitution_tag.
type MailsendTrackingSettingsSubscriptionTracking struct {

	// Indicates if this setting is enabled.
	Enable bool `json:"enable,omitempty"`

	// Text to be appended to the email, with the subscription tracking link. You may control where the link is by using the tag <% %>
	Text string `json:"text,omitempty"`

	// HTML to be appended to the email, with the subscription tracking link. You may control where the link is by using the tag <% %>
	Html string `json:"html,omitempty"`

	// A tag that will be replaced with the unsubscribe URL. for example: [unsubscribe_url]. If this parameter is used, it will override both the `text` and `html` parameters. The URL of the link will be placed at the substitution tag’s location, with no additional formatting.
	SubstitutionTag string `json:"substitution_tag,omitempty"`
}
