/*
 * SendGrid v3 API Documentation
 *
 * # The SendGrid Web API V3 Documentation  This is the entirety of the documented v3 endpoints. We have updated all the descriptions, parameters, requests, and responses.  ## Authentication   Every endpoint requires Authentication in the form of an Authorization Header:  Authorization: Bearer API_KEY
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package generated_type

type Body struct {

	// An array of messages and their metadata. Each object within personalizations can be thought of as an envelope - it defines who should receive an individual message and how that message should be handled.
	Personalizations []MailsendPersonalizations `json:"personalizations"`

	From *EmailObject `json:"from"`

	ReplyTo *EmailObject `json:"reply_to,omitempty"`

	// The global, or “message level”, subject of your email. This may be overridden by personalizations[x].subject.
	Subject string `json:"subject"`

	// An array in which you may specify the content of your email. You can include multiple mime types of content, but you must specify at least one mime type. To include more than one mime type, simply add another object to the array containing the `type` and `value` parameters.
	Content []MailsendContent `json:"content"`

	// An array of objects in which you can specify any attachments you want to include.
	Attachments []MailsendAttachments `json:"attachments,omitempty"`

	// The id of a template that you would like to use. If you use a template that contains a subject and content (either text or html), you do not need to specify those at the personalizations nor message level. 
	TemplateId string `json:"template_id,omitempty"`

	// An object of key/value pairs that define block sections of code to be used as substitutions.
	Sections *interface{} `json:"sections,omitempty"`

	// An object containing key/value pairs of header names and the value to substitute for them. You must ensure these are properly encoded if they contain unicode characters. Must not be one of the reserved headers.
	Headers *interface{} `json:"headers,omitempty"`

	// An array of category names for this message. Each category name may not exceed 255 characters. 
	Categories []string `json:"categories,omitempty"`

	// Values that are specific to the entire send that will be carried along with the email and its activity data. Substitutions will not be made on custom arguments, so any string that is entered into this parameter will be assumed to be the custom argument that you would like to be used. This parameter is overridden by personalizations[x].custom_args if that parameter has been defined. Total custom args size may not exceed 10,000 bytes.
	CustomArgs *interface{} `json:"custom_args,omitempty"`

	// A unix timestamp allowing you to specify when you want your email to be delivered. This may be overridden by the personalizations[x].send_at parameter. Scheduling more ta 72 hours in advance is forbidden.
	SendAt int32 `json:"send_at,omitempty"`

	// This ID represents a batch of emails to be sent at the same time. Including a batch_id in your request allows you include this email in that batch, and also enables you to cancel or pause the delivery of that batch. For more information, see https://sendgrid.com/docs/API_Reference/Web_API_v3/cancel_schedule_send.html 
	BatchId string `json:"batch_id,omitempty"`

	Asm *MailsendAsm `json:"asm,omitempty"`

	// The IP Pool that you would like to send this email from.
	IpPoolName string `json:"ip_pool_name,omitempty"`

	MailSettings *MailsendMailSettings `json:"mail_settings,omitempty"`

	TrackingSettings *MailsendTrackingSettings `json:"tracking_settings,omitempty"`
}
