/*
 * SendGrid v3 API Documentation
 *
 * # The SendGrid Web API V3 Documentation  This is the entirety of the documented v3 endpoints. We have updated all the descriptions, parameters, requests, and responses.  ## Authentication   Every endpoint requires Authentication in the form of an Authorization Header:  Authorization: Bearer API_KEY
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Allows you to enable tracking provided by Google Analytics.
type MailsendTrackingSettingsGanalytics struct {

	// Indicates if this setting is enabled.
	Enable bool `json:"enable,omitempty"`

	// Name of the referrer source. (e.g. Google, SomeDomain.com, or Marketing Email)
	UtmSource string `json:"utm_source,omitempty"`

	// Name of the marketing medium. (e.g. Email)
	UtmMedium string `json:"utm_medium,omitempty"`

	// Used to identify any paid keywords. 
	UtmTerm string `json:"utm_term,omitempty"`

	// Used to differentiate your campaign from advertisements. 
	UtmContent string `json:"utm_content,omitempty"`

	// The name of the campaign. 
	UtmCampaign string `json:"utm_campaign,omitempty"`
}
