/*
 * SendGrid v3 API Documentation
 *
 * # The SendGrid Web API V3 Documentation  This is the entirety of the documented v3 endpoints. We have updated all the descriptions, parameters, requests, and responses.  ## Authentication   Every endpoint requires Authentication in the form of an Authorization Header:  Authorization: Bearer API_KEY
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A collection of different mail settings that you can use to specify how you would like this email to be handled.
type MailsendMailSettings struct {

	Bcc *MailsendMailSettingsBcc `json:"bcc,omitempty"`

	BypassListManagement *MailsendMailSettingsBypassListManagement `json:"bypass_list_management,omitempty"`

	Footer *MailsendMailSettingsFooter `json:"footer,omitempty"`

	SandboxMode *MailsendMailSettingsSandboxMode `json:"sandbox_mode,omitempty"`

	SpamCheck *MailsendMailSettingsSpamCheck `json:"spam_check,omitempty"`
}
